[project]
name = "in-memory-app"
version = "0.1.0"
description = "In memory app using SingleStore and Memcached."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymemcache>=4.0.0",
    "singlestoredb>=1.16.4",
]

[project.scripts]
cli = "src.cli:main"
